name: Actions

on: [push, pull_request]

jobs:
  other-job1:
    name: Other  Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run action
      run: |
        netstat -lan
   
