name: Actions

on: [push, pull_request]
env:
  LANG: en_US.UTF-8 


jobs:
  other-job1:
   
    name: Other  Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run action
      env:
        testit: ${{toJson(runner)}}
        testit2: ${{toJson(steps)}} 
        testit3: ${{toJson(github)}} 
      run: |
        echo $LANG
        echo $testit
        echo $testit2
        echo $testit3



   
