name: Actions

on: [push, pull_request]
env:
  LANG: en_US.UTF-8 


jobs:
  other-job1:
   
    name: Other  Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category: [main, data1, data2]
        include:
          - category: main
            mysql: true
          - category: data1
            postgres: true
          - category: data2
            mysql: true
            postgres: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start Mysql?
      if: ${{matrix.mysql}}
      run: echo "LAUNCH MYSQL!!
    - name: Start Postgres?
      if: ${{matrix.postgres}}
      run: echo "LAUNCH POSTGRES!!
    



   
