name: Actions

on: [push, pull_request]
env:
  LANG: en_US.UTF-8 


jobs:
  
  blah:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
     
  footrue:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1
  foofalse:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
        
  
  other-job1:
    needs: foo${{github.repository == protean-project/fun}}
    if: failure() == false
    name: Other ${{matrix.category}}
    timeout-minutes: ${{matrix.timeout}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category: [main, data1, data2]
        include:
          - category: main
            test: >
               one
               two
               three
            mysql: true
            timeout: 1
          - category: data1
            postgres: true
            timeout: 4
          - category: data2
            mysql: true
            postgres: true
            timeout: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start Mysql?
      if: matrix.mysql
      run: echo "LAUNCH MYSQL!!"
    - name: Start Postgres?
      if: matrix.postgres
      run: echo "LAUNCH POSTGRES!!"
    - name: Echo Stuff
      env:
        MSG: ${{matrix.test}}  
      run: |
        echo $MSG
        sleep 70



   
